### ISSUE TITLE
APIv3 or APIv4

### ISSUE THREAD

**Issue by phillipadsmith** [TechToThePeople/node-civicrm#5]
I'm guessing this client is for APIv3, but just wanted to confirm that is correct.

Thanks!

Phillip.

**Comment by MikeyMJCO** [comment]
Yes, APIv4 does not have a REST interface at present.

**Comment by herbdool** [comment]
Now Api4 has a REST interface, wondering if this repo could support it too or if there should be a spin off.

I haven't tried this repo yet to see if it still works with recent versions of the packages.

**Comment by tttp** [comment]
Hi,

it works with v3, indeed, no v4, you're welcome to add it to the repo if you have a need that doesn't work with v3

**Comment by herbdool** [comment]
I was going to use this in combination with Cypress for testing, but I ended up just calling api4 rest directly from Cypress since it includes the Request library already. Does the job for the small amount of calls the testing needs to do.
